import type { FraudAccount, SuspiciousTransaction } from "@/types/aml";

export const flaggedFraudAccounts: FraudAccount[] = [
  {
    accountId: "ACC-90421",
    holderName: "Rivermark Exports Ltd",
    transactionId: "TXN-771034",
    amount: 1284500,
    country: "UAE -> India",
    riskScore: 96,
    riskIndicators: ["Invoice mismatch", "Round-dollar layering", "Shell intermediary"],
    tradeDetails: "Electronics consignment with inconsistent valuation.",
    status: "high",
  },
  {
    accountId: "ACC-55190",
    holderName: "Helios Shipping AG",
    transactionId: "TXN-771281",
    amount: 845000,
    country: "Turkey -> Singapore",
    riskScore: 91,
    riskIndicators: ["Rapid pass-through", "High-risk corridor"],
    tradeDetails: "Steel coils rerouted across two free-trade zones.",
    status: "high",
  },
  {
    accountId: "ACC-33489",
    holderName: "Nexa Petrochem DMCC",
    transactionId: "TXN-771416",
    amount: 2195000,
    country: "Oman -> Kenya",
    riskScore: 94,
    riskIndicators: ["Beneficial owner discrepancy", "Back-dated documentation"],
    tradeDetails: "Petrochemical shipment flagged for unusual split invoicing.",
    status: "high",
  },
  {
    accountId: "ACC-70013",
    holderName: "BlueHarbor Traders",
    transactionId: "TXN-771522",
    amount: 665000,
    country: "China -> Nigeria",
    riskScore: 89,
    riskIndicators: ["Dual-use commodity", "Repeated near-threshold values"],
    tradeDetails: "Industrial valves with recurring undervaluation pattern.",
    status: "high",
  },
  {
    accountId: "ACC-10277",
    holderName: "Arcstone Commodities",
    transactionId: "TXN-771600",
    amount: 1499000,
    country: "Vietnam -> UAE",
    riskScore: 92,
    riskIndicators: ["Third-party payment", "Counterparty age anomaly"],
    tradeDetails: "Agricultural goods routed through newly incorporated buyer.",
    status: "high",
  },
  {
    accountId: "ACC-82111",
    holderName: "Lumen Textile House",
    transactionId: "TXN-771661",
    amount: 437000,
    country: "Bangladesh -> UK",
    riskScore: 87,
    riskIndicators: ["HS code inconsistency", "Shipment quantity variance"],
    tradeDetails: "Textile export with inconsistent customs classification.",
    status: "high",
  },
];

export const suspiciousTransactions: SuspiciousTransaction[] = [
  {
    transactionId: "STX-202601",
    sender: "Zenith Agro Pvt Ltd",
    receiver: "Marlin Foods PLC",
    amount: 275000,
    tradeType: "Food Commodities",
    suspicionReason: "Unusual unit pricing and urgent settlement request",
    riskLevel: "medium",
    status: "suspicious",
  },
  {
    transactionId: "STX-202614",
    sender: "Coral Engineering",
    receiver: "Delta Machining SA",
    amount: 580000,
    tradeType: "Machinery",
    suspicionReason: "Inconsistent supplier documentation",
    riskLevel: "medium",
    status: "suspicious",
  },
  {
    transactionId: "STX-202627",
    sender: "Aster Pharma Distributors",
    receiver: "NordMed BV",
    amount: 430000,
    tradeType: "Pharmaceutical",
    suspicionReason: "Counterparty appears on prior watchlist entries",
    riskLevel: "medium",
    status: "suspicious",
  },
  {
    transactionId: "STX-202635",
    sender: "Orchid Metals LLC",
    receiver: "Silverline Foundry",
    amount: 790000,
    tradeType: "Industrial Metals",
    suspicionReason: "Repeated route changes before shipment",
    riskLevel: "medium",
    status: "suspicious",
  },
  {
    transactionId: "STX-202644",
    sender: "Nimbus Trading Co",
    receiver: "FreshGrid Retail",
    amount: 198000,
    tradeType: "Consumer Goods",
    suspicionReason: "Mismatch between invoice terms and payment speed",
    riskLevel: "medium",
    status: "suspicious",
  },
  {
    transactionId: "STX-202659",
    sender: "Vantage Marine",
    receiver: "Pacific Bulk Imports",
    amount: 620000,
    tradeType: "Shipping Equipment",
    suspicionReason: "Layered intermediaries with thin corporate history",
    riskLevel: "medium",
    status: "suspicious",
  },
];

export const accountOptions = [
  "ACC-90421",
  "ACC-55190",
  "ACC-33489",
  "ACC-70013",
  "ACC-10277",
  "ACC-82111",
  "ACC-22001",
  "ACC-22002",
  "ACC-22003",
  "ACC-22004",
];

export const commodityOptions = [
  "Electronics",
  "Textiles",
  "Steel",
  "Petrochemicals",
  "Agricultural Produce",
  "Industrial Equipment",
];

export const routeOptions = [
  "UAE -> India",
  "Turkey -> Singapore",
  "Oman -> Kenya",
  "China -> Nigeria",
  "Vietnam -> UAE",
  "Bangladesh -> UK",
  "Germany -> South Africa",
];
