import type { FraudAccount, StrReport, SuspiciousTransaction } from "@/types/aml";

type EmailTemplate = {
  subject: string;
  html: string;
  text: string;
};

const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(amount);

const toBulletHtml = (lines: string[]): string =>
  lines.map((line) => `<li style="margin: 0 0 6px 0;">${line}</li>`).join("");

export const buildFraudComplianceTemplate = (account: FraudAccount, report: StrReport): EmailTemplate => {
  const subject = `[TBML Alert] STR ready for review - ${account.transactionId}`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Suspicious Transaction Report Ready</h2>
      <p style="margin-top: 0; color: #334155;">Please review the generated STR and proceed with internal escalation workflow.</p>

      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Account:</strong> ${account.holderName} (${account.accountId})</p>
        <p><strong>Transaction:</strong> ${account.transactionId}</p>
        <p><strong>Amount:</strong> ${formatCurrency(account.amount)}</p>
        <p><strong>Country Route:</strong> ${account.country}</p>
      </div>

      <h3 style="margin-bottom: 8px;">Report Summary</h3>
      <ul style="padding-left: 20px; margin-top: 0;">
        ${toBulletHtml([
          `Executive Summary: ${report.executiveSummary}`,
          `Transaction Details: ${report.transactionDetails}`,
          `Risk Indicators: ${report.riskIndicators}`,
          `Recommendation: ${report.recommendation}`,
        ])}
      </ul>

      <p style="color: #475569; font-size: 12px;">Generated by TBML dashboard automated workflow.</p>
    </div>
  `;

  const text = [
    "Suspicious Transaction Report Ready",
    "",
    `Account: ${account.holderName} (${account.accountId})`,
    `Transaction: ${account.transactionId}`,
    `Amount: ${formatCurrency(account.amount)}`,
    `Country Route: ${account.country}`,
    "",
    "Report Summary",
    `Executive Summary: ${report.executiveSummary}`,
    `Transaction Details: ${report.transactionDetails}`,
    `Risk Indicators: ${report.riskIndicators}`,
    `Recommendation: ${report.recommendation}`,
  ].join("\n");

  return { subject, html, text };
};

export const buildFraudBankAlertTemplate = (account: FraudAccount, report: StrReport): EmailTemplate => {
  const subject = `[Urgent] Fraud alert request for ${account.transactionId}`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Urgent fraud coordination request</h2>
      <p style="margin-top: 0; color: #334155;">Dear ${account.originatingBank} Fraud Operations Team,</p>
      <p>Transaction <strong>${account.transactionId}</strong> has been classified as high fraud risk by our monitoring controls.</p>
      <p>Please initiate urgent verification and containment actions on your side and share your action outcome.</p>

      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Account Holder:</strong> ${account.holderName}</p>
        <p><strong>Account ID:</strong> ${account.accountId}</p>
        <p><strong>Transaction ID:</strong> ${account.transactionId}</p>
        <p><strong>Amount:</strong> ${formatCurrency(account.amount)}</p>
        <p><strong>Route:</strong> ${account.country}</p>
      </div>

      <h3 style="margin-bottom: 8px;">STR Highlights</h3>
      <ul style="padding-left: 20px; margin-top: 0;">
        ${toBulletHtml([
          `Executive Summary: ${report.executiveSummary}`,
          `Transaction Details: ${report.transactionDetails}`,
          `Risk Indicators: ${report.riskIndicators}`,
          `Recommendation: ${report.recommendation}`,
        ])}
      </ul>

      <p style="color: #475569; font-size: 12px;">This is an automated fraud escalation from TBML Monitoring.</p>
    </div>
  `;

  const text = [
    "Urgent fraud coordination request",
    `Dear ${account.originatingBank} Fraud Operations Team,`,
    "",
    `Transaction ${account.transactionId} has been classified as high fraud risk by our monitoring controls.`,
    "Please initiate urgent verification and containment actions and share your action outcome.",
    "",
    `Account Holder: ${account.holderName}`,
    `Account ID: ${account.accountId}`,
    `Transaction ID: ${account.transactionId}`,
    `Amount: ${formatCurrency(account.amount)}`,
    `Route: ${account.country}`,
    "",
    "STR Highlights",
    `Executive Summary: ${report.executiveSummary}`,
    `Transaction Details: ${report.transactionDetails}`,
    `Risk Indicators: ${report.riskIndicators}`,
    `Recommendation: ${report.recommendation}`,
  ].join("\n");

  return { subject, html, text };
};

export const buildSuspiciousComplianceTemplate = (transaction: SuspiciousTransaction): EmailTemplate => {
  const subject = `[Review] Suspicious transaction inquiry initiated - ${transaction.transactionId}`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Suspicious case inquiry initiated</h2>
      <p style="margin-top: 0; color: #334155;">A formal request for clarification has been sent to the originating bank.</p>

      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Transaction ID:</strong> ${transaction.transactionId}</p>
        <p><strong>Sender:</strong> ${transaction.sender}</p>
        <p><strong>Receiver:</strong> ${transaction.receiver}</p>
        <p><strong>Amount:</strong> ${formatCurrency(transaction.amount)}</p>
        <p><strong>Trade Type:</strong> ${transaction.tradeType}</p>
      </div>
      <p style="color: #475569; font-size: 12px;">Automated by TBML suspicious-case workflow.</p>
    </div>
  `;

  const text = [
    `Suspicious case inquiry initiated`,
    `A formal request has been prepared and notifications will be sent to relevant accounts and compliance.`,

    `Transaction ID: ${transaction.transactionId}`,
    `Sender: ${transaction.sender}`,
    `Receiver: ${transaction.receiver}`,
    `Amount: ${formatCurrency(transaction.amount)}`,
    `Trade Type: ${transaction.tradeType}`,
  ].join("\n");

  return { subject, html, text };
};

export const buildSuspiciousBankInquiryTemplate = (transaction: SuspiciousTransaction): EmailTemplate => {
  const subject = `Request for transaction clarification - ${transaction.transactionId}`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Request for clarification</h2>
      <p style="margin-top: 0; color: #334155;">Dear ${transaction.originatingBank} Compliance Team,</p>
      <p>This transaction has been marked as suspicious by our monitoring system.</p>
      <p>Please review the account transaction history and supporting documents for the related account holder, and respond with any clarifying information within 48 hours.</p>

      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Sender:</strong> ${transaction.sender}</p>
        <p><strong>Receiver:</strong> ${transaction.receiver}</p>
        <p><strong>Amount:</strong> ${formatCurrency(transaction.amount)}</p>
        <p><strong>Trade Type:</strong> ${transaction.tradeType}</p>
      </div>
      <p style="color: #475569; font-size: 12px;">This communication is generated by TBML Monitoring for due-diligence coordination.</p>
    </div>
  `;

  const text = [
    "Request for clarification",
    `Dear ${transaction.originatingBank} Compliance Team,`,
    "",
    `This transaction has been marked suspicious by our monitoring system. Please review account transaction history and provide any supporting documents or assessment within 48 hours.`,
    "",
    `Sender: ${transaction.sender}`,
    `Receiver: ${transaction.receiver}`,
    `Amount: ${formatCurrency(transaction.amount)}`,
    `Trade Type: ${transaction.tradeType}`,
  ].join("\n");

  return { subject, html, text };
};

export const buildFreezeAccountTemplate = (
  account: FraudAccount,
  bankName: string,
  bankRole: "Sender" | "Receiver",
): EmailTemplate => {
  const subject = `[Action Required] Freeze account linked to ${account.transactionId}`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Urgent account freeze request</h2>
      <p style="margin-top: 0; color: #334155;">Dear ${bankName} ${bankRole} Bank Compliance Team,</p>
      <p>Based on AML review, we request immediate temporary freeze controls for accounts connected to transaction <strong>${account.transactionId}</strong>.</p>

      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Transaction ID:</strong> ${account.transactionId}</p>
        <p><strong>Account:</strong> ${account.accountId}</p>
        <p><strong>Amount:</strong> ${formatCurrency(account.amount)}</p>
        <p><strong>Route:</strong> ${account.country}</p>
        <p><strong>Risk Indicators:</strong> ${account.riskIndicators.join(", ")}</p>
      </div>
      <p>Please confirm freeze execution and provide next-step investigation notes.</p>
      <p style="color: #475569; font-size: 12px;">Generated by TBML dashboard action workflow.</p>
    </div>
  `;

  const text = [
    "Urgent account freeze request",
    `Dear ${bankName} ${bankRole} Bank Compliance Team,`,
    "",
    `Please apply temporary freeze controls for accounts linked to ${account.transactionId}.`,
    "",
    `Transaction ID: ${account.transactionId}`,
    `Account: ${account.accountId}`,
    `Amount: ${formatCurrency(account.amount)}`,
    `Route: ${account.country}`,
    `Risk Indicators: ${account.riskIndicators.join(", ")}`,
    "",
    "Please confirm freeze execution and share next-step investigation notes.",
  ].join("\n");

  return { subject, html, text };
};

export const buildDocumentRequestTemplate = (
  account: FraudAccount,
  bankName: string,
  bankRole: "Sender" | "Receiver",
): EmailTemplate => {
  const subject = `[Documents Requested] ${account.transactionId} enhanced review`;

  const html = `
    <div style="font-family: Arial, sans-serif; line-height: 1.5; color: #0f172a; max-width: 680px; margin: 0 auto;">
      <h2 style="margin-bottom: 6px;">Request for additional documents</h2>
      <p style="margin-top: 0; color: #334155;">Dear ${bankName} ${bankRole} Bank Team,</p>
      <p>For transaction <strong>${account.transactionId}</strong>, please share additional supporting records for compliance review.</p>
      <ul style="padding-left: 20px; margin-top: 8px;">
        ${toBulletHtml([
          "Full KYC and beneficial ownership records",
          "Underlying trade invoice, bill of lading, and customs declaration",
          "Payment instructions and source-of-funds evidence",
          "Internal transaction risk assessment notes",
        ])}
      </ul>
      <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px; margin: 16px 0;">
        <p><strong>Transaction ID:</strong> ${account.transactionId}</p>
        <p><strong>Amount:</strong> ${formatCurrency(account.amount)}</p>
        <p><strong>Route:</strong> ${account.country}</p>
      </div>
      <p style="color: #475569; font-size: 12px;">Generated by TBML dashboard action workflow.</p>
    </div>
  `;

  const text = [
    "Request for additional documents",
    `Dear ${bankName} ${bankRole} Bank Team,`,
    "",
    `For transaction ${account.transactionId}, please share supporting records for compliance review:`,
    "- Full KYC and beneficial ownership records",
    "- Underlying trade invoice, bill of lading, and customs declaration",
    "- Payment instructions and source-of-funds evidence",
    "- Internal transaction risk assessment notes",
    "",
    `Amount: ${formatCurrency(account.amount)}`,
    `Route: ${account.country}`,
  ].join("\n");

  return { subject, html, text };
};



